[UNITTEST] env

diff --git a/unittest_env b/unittest_env
--- a/unittest_env
+++ b/unittest_env
@@ -1,6 +1,19 @@
 echo "TESTING ENV"
-echo "Simple env :"
+echo -e "\nENV NO ARGUMENTS"
 env
-echo "Diff env and /usr/bin/env :"
-env > /tmp/test_env && /usr/bin/env > /tmp/test_bin_env && diff /tmp/test_env /tmp/test_bin_env
+echo "ret: $?"
+env > /tmp/env_original
+
+echo -e "\nENV OPTIONS"
+echo -e "\t
+
+echo -e "\nENV ERRORS"
+env -Z
+echo "ret: $?"
+env > /tmp/env_save
+diff /tmp/env_original /tmp/env_save
+
+
+
+rm -f /tmp/env_save
 echo OK
