[UNITTEST] env

diff --git a/unittest_env b/unittest_env
--- a/unittest_env
+++ b/unittest_env
@@ -1,66 +1,82 @@
+echo "------------------------------------------------"
 echo "TESTING ENV"
-echo -e "\nENV NO ARGUMENTS"
+echo "------------------------------------------------"
+
+echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
+echo -e "ENV NO ARGUMENTS"
 env
 echo "ret: $?"
 env > /tmp/env_original
 
-echo -e "\nENV OPTIONS"
+echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
+echo -e "ENV OPTIONS"
 echo -e "\tERASE ENVIRONMENT: -i"
 env -i
 echo "ret: $?"
 echo -e "\tERASE ENVIRONMENT: -i ls"
 env -i ls
-echo "ret: $?"
+echo "env -i ls (ret: $?)"
 
 echo -e "\tMODIFY PATH: -P"
 env -P
-echo "ret: $?"
+echo "env -P (ret: $?)"
 echo -e "\tMODIFY PATH: -P /bin"
 echo -e "\t\$PATH: $PATH"
 env -P /bin
-echo "ret: $?"
+echo "env -P /bin (ret: $?)"
 echo -e " \$PATH: $PATH"
+
 echo -e "\tMODIFY PATH: -P/bin"
 echo -e " \$PATH: $PATH"
 env -P/bin
-echo "ret: $?"
+echo "env -P/bin (ret: $?)"
 echo -e " \$PATH: $PATH"
+
 echo -e "\tMODIFY PATH: -P /bin ls"
 echo -e " \$PATH: $PATH"
 env -P /bin ls
-echo "ret: $?"
+echo "env -P /bin ls (ret: $?)"
 echo -e " \$PATH: $PATH"
+
 echo -e "\tMODIFY PATH: -P /bin env"
 echo -e " \$PATH: $PATH"
 env -P /bin env
-echo "ret: $?"
+echo "env -P /bin env (ret: $?)"
 echo -e " \$PATH: $PATH"
 
 echo -e "\tUNSET VARIABLE: -u"
 env -u
-echo "ret: $?"
+echo "env -u (ret: $?)"
+
 echo -e "\tUNSET VARIABLE: -uPATH"
 env -uPATH
-echo "ret: $?"
-echo -e " \$PATH: $PATH"
-echo -e "\tUNSET VARIABLE: -u PATH"
-env -u PATH
-echo "ret: $?"
-echo -e " \$PATH: $PATH"
-echo -e "\tUNSET VARIABLE: -u PATH ls"
-env -u PATH ls
-echo "ret: $?"
+echo "env -uPATH (ret: $?)"
 echo -e " \$PATH: $PATH"
 
+echo -e "\tUNSET VARIABLE: -u PATH"
+env -u PATH
+echo "env -u PATH (ret: $?)"
+echo -e " \$PATH: $PATH"
+
+echo -e "\tUNSET VARIABLE: -u PATH ls"
+env -u PATH ls
+echo "env -u PATH ls (ret: $?)"
+echo -e " \$PATH: $PATH"
 
 echo -e "\tVERBOSE MODE: -v"
 env -v
-echo "ret: $?"
+echo "env -v (ret: $?)"
+
+echo -e "\tVERBOSE MODE: -vvvvvvvvvvvv"
+env -vvvvvvvvvvvv
+echo "env -vvvvvvvvvvvv (ret: $?)"
+
 echo -e "\tVERBOSE MODE: -vi"
 env -vi
 echo "ret: $?"
 
-echo -e "\nENV ERRORS"
+echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
+echo -e "ENV ERRORS"
 env -Z
 echo "ret: $?"
 env > /tmp/env_save
